### ISSUE TITLE
Cann't enable embedly button

### ISSUE THREAD

**Issue by slavarazum** [alfonsobries/nova-froala-editor#1]
Trying to enable ability to paste embed content
![Embedly button](https://image.prntscr.com/image/pjaC5YpBSEaysF37t5o-yA.png)

Field options:
```php
$TextEditor->options([
            'toolbarButtons' => [
                'bold',
                'italic',
                'underline',
                'strikeThrough',
                '|',
                'formatOL',
                'formatUL',
                '|',
                'insertFile',
                'insertImage',
                'insertLink',
                'insertVideo',
                '|',
                'emoticons',
                'embedly', // Here
                'inlineStyle',
                'paragraphFormat',
                'paragraphStyle',
                'quote',
                'specialCharacters',
                '|',
                'html',
                'fullscreen'
            ]
        ]);
```
Button doesn't appear, no console or network errors.

**Comment by slavarazum** [comment]
@alfonsobries Your thoughts, how we can fix it?
I have tried to include
```js
<script src="https://cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
```
according with [Froala Documentation](https://www.froala.com/wysiwyg-editor/examples/embedly), by
```php
\Laravel\Nova\Nova::remoteScript('https://cdn.embedly.com/widgets/platform.js');
```
it was appear in scripts, but button still hasn't appears
![Screenshot](https://image.prntscr.com/image/stS6lvaRQJSD9xxbt2Fq0g.png)

**Comment by alfonsobries** [comment]
@ModernArtisan I tried to add the scripts also with no luck I think that the issue is related with the vue-froala-wysiwyg package that this depends on, I will try to fix that package and make a PR or maybe I think that I probably need to make my custom Vue component.

**Comment by slavarazum** [comment]
Have created issue on froala repository - https://github.com/froala/wysiwyg-editor/issues/3040
Looks like problem not related to `vue-froala-wysiwyg`, have the same behavior with jQuery plugin.
